name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres:14.1-alpine
        env:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=loggaroo
        volumes:
          - db:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        # Set health checks to wait until postgres has started
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U admin -d loggaroo" ]
          interval: 5s
          timeout: 5s
          retries: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Format
        run: cargo fmt --check --verbose
      - name: Clippy
        run: cargo clippy --verbose
      - name: Test
        run: cargo test --verbose