name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: loggaroo
        volumes:
          - db:/var/lib/postgresql/data
          - ../../init.sql:/docker-entrypoint-initdb.d/init.sql
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Format
        run: cargo fmt --check --verbose
      - name: Clippy
        run: cargo clippy --verbose
      - name: Test
        run: cargo test --verbose